/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "smartknob.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(PB_FromSmartKnob, PB_FromSmartKnob, 2)


PB_BIND(PB_ToSmartknob, PB_ToSmartknob, AUTO)


PB_BIND(PB_Ack, PB_Ack, AUTO)


PB_BIND(PB_Log, PB_Log, 2)


PB_BIND(PB_SmartKnobState, PB_SmartKnobState, AUTO)


PB_BIND(PB_SmartKnobConfig, PB_SmartKnobConfig, AUTO)


PB_BIND(PB_RequestState, PB_RequestState, AUTO)


PB_BIND(PB_PersistentConfiguration, PB_PersistentConfiguration, AUTO)


PB_BIND(PB_MotorCalibration, PB_MotorCalibration, AUTO)


PB_BIND(PB_StrainCalibration, PB_StrainCalibration, AUTO)



